kitsudaiki/libKitsunemimiCommon

README.md
include/libKitsuneCommon/common_items/table_item.h
src/common_items/table_item.cpp
tests/libKitsuneCommon/common_items/table_item_test.cpp

Update separator line in table items

---

README.md
include/libKitsuneCommon/common_items/table_item.h
src/common_items/table_item.cpp
tests/libKitsuneCommon/common_items/table_item_test.cpp

Multiline rows in table items

---

include/libKitsuneCommon/common_items/table_item.h
src/common_items/table_item.cpp

complete rewrite of the methods, which prepare the table content for the output
to make the code cleaner and later updates easier.

cleanup methods for table-output

---

README.md
include/libKitsuneCommon/common_items/table_item.h
src/common_items/table_item.cpp
tests/libKitsuneCommon/common_items/table_item_test.cpp

Optional vertical table output

---

README.md
include/libKitsuneCommon/common_items/data_items.h
include/libKitsuneCommon/common_items/table_item.h
src/common_items/data_items.cpp
src/common_items/table_item.cpp
tests/libKitsuneCommon/common_items/data_items_DataArray_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataArray_test.h
tests/libKitsuneCommon/common_items/data_items_DataObject_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataObject_test.h
tests/libKitsuneCommon/common_items/data_items_DataValue_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataValue_test.h
tests/libKitsuneCommon/common_items/table_item_test.cpp
tests/libKitsuneCommon/common_items/table_item_test.h

renamed in data-items:
- print -> toString
- toString -> getString
- getString(...) -> getStringByKey(...)
renamed in table-items
- print -> toString
close #24

renamed print-methods

---

README.md
include/libKitsuneCommon/common_items/data_items.h
include/libKitsuneCommon/common_items/table_item.h
src/common_items/data_items.cpp
src/common_items/table_item.cpp
tests/libKitsuneCommon/common_items/data_items_DataArray_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataArray_test.h
tests/libKitsuneCommon/common_items/data_items_DataMap_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataMap_test.h
tests/libKitsuneCommon/common_items/data_items_DataValue_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataValue_test.h
tests/main.cpp
tests/tests.pro

Rename data object

---

include/libKitsuneCommon/common_items/table_item.h
src/common_items/table_item.cpp
tests/libKitsuneCommon/common_items/table_item_test.cpp
tests/libKitsuneCommon/common_items/table_item_test.h

added new function to clear table-items by resetting them to the empty
default.

add clear-table-function

---

include/libKitsuneCommon/common_items/data_items.h
src/common_items/data_items.cpp
tests/libKitsuneCommon/common_items/data_items_DataArray_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataMap_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataValue_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataValue_test.h

Added new constructor, getter and setter for boolean-values and updated all unit-tests.

added boolean-values to DataValue-class

---

include/libKitsuneCommon/common_items/data_items.h
src/common_items/data_items.cpp
tests/libKitsuneCommon/common_items/data_items_DataArray_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataArray_test.h
tests/libKitsuneCommon/common_items/data_items_DataMap_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataMap_test.h
tests/libKitsuneCommon/common_items/data_items_DataValue_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataValue_test.h

Added copy-assignment-operator to DataArray, DataMap and DataValue together with tests.

add copy-assignment-operator

---

include/libKitsuneCommon/common_items/data_items.h
src/common_items/data_items.cpp
tests/libKitsuneCommon/common_items/data_items_DataArray_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataArray_test.h
tests/libKitsuneCommon/common_items/data_items_DataMap_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataMap_test.h
tests/libKitsuneCommon/common_items/data_items_DataValue_test.cpp
tests/libKitsuneCommon/common_items/data_items_DataValue_test.h

Added copy-assignment-constructor to DataValue, DataMap and DataArray.
Also added tests for the new constructor.

add copy-assignment-constructor

---

CHANGELOG
README.md
include/libKitsuneCommon/statemachine.h
src/state.h
src/statemachine.cpp
tests/libKitsuneCommon/state_test.cpp
tests/libKitsuneCommon/state_test.h
tests/libKitsuneCommon/statemachine_test.cpp
tests/libKitsuneCommon/statemachine_test.h

Add parent state to statemachine

---

include/libKitsuneCommon/thread.h
src/thread.cpp

Add spin lock to thread

---

include/libKitsunemimiCommon/common_methods/string_methods.h
include/libKitsunemimiCommon/process_execution.h
src/common_items/table_item.cpp
src/process_execution.cpp
src/src.pro
tests/libKitsunemimiCommon/common_methods/string_methods_test.cpp
tests/libKitsunemimiCommon/common_methods/string_methods_test.h

- added new string-replace-method
- updated split-string-methods
- added method to run executables
- new unit-tests

Add run command methods

---

CHANGELOG
README.md
src/src.pro

updates for tagging 0.9.0
- unit-tests

changes for tag 0.9.0

---

include/libKitsunemimiCommon/common_items/data_items.h
include/libKitsunemimiCommon/data_buffer.h
src/common_items/data_items.cpp
tests/libKitsunemimiCommon/common_items/data_items_DataArray_test.cpp
tests/libKitsunemimiCommon/common_items/data_items_DataArray_test.h
tests/libKitsunemimiCommon/common_items/data_items_DataMap_test.cpp
tests/libKitsunemimiCommon/common_items/data_items_DataMap_test.h
tests/libKitsunemimiCommon/common_items/data_items_DataValue_test.cpp
tests/libKitsunemimiCommon/common_items/data_items_DataValue_test.h
tests/libKitsunemimiCommon/data_buffer_test.cpp

- fixes for data-items
- add clear-method to data-items
- update data-buffer-methods
- updated unit-tests

More updates

---

CHANGELOG
README.md
src/src.pro

updates for tag 0.10.0
- unit-tests

updates for tag 0.10.0

---

CHANGELOG
README.md
src/src.pro

updates for tagging 0.10.1
- unit-tests

updates for tagging 0.10.1

---

defaults.pri
include/libKitsunemimiCommon/benchmark_test.h
src/benchmark_test.cpp
src/src.pro

add simple helper-class for benchmarks
- close #4

add simple helper-class for benchmarks

---

include/libKitsunemimiCommon/test_helper/compare_test_helper.h
include/libKitsunemimiCommon/test_helper/speed_test_helper.h
src/src.pro
src/test_helper/compare_test_helper.cpp
src/test_helper/speed_test_helper.cpp
tests/libKitsunemimiCommon/common_items/data_items_DataArray_test.cpp
tests/libKitsunemimiCommon/common_items/data_items_DataArray_test.h
tests/libKitsunemimiCommon/common_items/data_items_DataMap_test.cpp
tests/libKitsunemimiCommon/common_items/data_items_DataMap_test.h
tests/libKitsunemimiCommon/common_items/data_items_DataValue_test.cpp
tests/libKitsunemimiCommon/common_items/data_items_DataValue_test.h
tests/libKitsunemimiCommon/common_items/table_item_test.cpp
tests/libKitsunemimiCommon/common_items/table_item_test.h
tests/libKitsunemimiCommon/common_methods/string_methods_test.cpp
tests/libKitsunemimiCommon/common_methods/string_methods_test.h
tests/libKitsunemimiCommon/common_methods/vector_methods_test.cpp
tests/libKitsunemimiCommon/common_methods/vector_methods_test.h
tests/libKitsunemimiCommon/data_buffer_test.cpp
tests/libKitsunemimiCommon/data_buffer_test.h
tests/libKitsunemimiCommon/state_test.cpp
tests/libKitsunemimiCommon/state_test.h
tests/libKitsunemimiCommon/statemachine_test.cpp
tests/libKitsunemimiCommon/statemachine_test.h

Restructure tests

---

CHANGELOG
README.md
src/src.pro

updates for tag 0.11.0

---

include/libKitsunemimiCommon/buffer/ring_buffer.h
include/libKitsunemimiCommon/buffer/stack_buffer.h
include/libKitsunemimiCommon/buffer/stack_buffer_reserve.h
tests/libKitsunemimiCommon/buffer/stack_buffer_test.cpp
tests/libKitsunemimiCommon/buffer/stack_buffer_test.h

add local stack-buffer-reserve and added some comments
- close #82 
- unit-tests

add local stack-buffer-reserve and added some comments

---

CHANGELOG
README.md
include/libKitsunemimiCommon/buffer/ring_buffer.h
include/libKitsunemimiCommon/buffer/stack_buffer.h
include/libKitsunemimiCommon/buffer/stack_buffer_reserve.h
include/libKitsunemimiCommon/common_items/data_items.h
include/libKitsunemimiCommon/common_items/table_item.h
src/buffer/stack_buffer_reserve.cpp
src/src.pro
tests/libKitsunemimiCommon/buffer/stack_buffer_reserve_test.cpp
tests/libKitsunemimiCommon/buffer/stack_buffer_test.cpp
tests/libKitsunemimiCommon/buffer/stack_buffer_test.h

updates for tag 0.12.0
- unit-tests

Tag 0.12.0

---

CHANGELOG
src/src.pro

update for tagging 0.12.1
- unit-tests

update for tagging 0.12.1

---

CHANGELOG
README.md
include/libKitsunemimiCommon/buffer/data_buffer.h
include/libKitsunemimiCommon/buffer/ring_buffer.h
include/libKitsunemimiCommon/buffer/stack_buffer.h
src/src.pro
tests/unit_tests/libKitsunemimiCommon/buffer/data_buffer_test.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/data_buffer_test.h
tests/unit_tests/libKitsunemimiCommon/buffer/ring_buffer_test.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/ring_buffer_test.h
tests/unit_tests/libKitsunemimiCommon/buffer/stack_buffer_test.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/stack_buffer_test.h

Renamings in the buffer-structures and updates for tagging 0.13.0
- unit-tests

Tag 0.13.0

---

include/libKitsunemimiCommon/common_methods/string_methods.h
include/libKitsunemimiCommon/common_methods/vector_methods.h
src/common_methods/string_methods.cpp
src/common_methods/vector_methods.cpp
src/src.pro
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.h
tests/unit_tests/libKitsunemimiCommon/common_methods/vector_methods_test.cpp

update common methods
- unit-tests

Update common methods

---

include/libKitsunemimiCommon/buffer/data_buffer.h
tests/unit_tests/libKitsunemimiCommon/buffer/data_buffer_test.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/data_buffer_test.h

- add assignment operator to data-buffer
- unit-tests

add assignment operator to databuffer

---

README.md
include/libKitsunemimiCommon/common_methods/string_methods.h
src/common_items/data_items.cpp
src/common_methods/string_methods.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.h

- add function to trim string
- new unit-tests

Add trim functions

---

include/libKitsunemimiCommon/buffer/data_buffer.h
include/libKitsunemimiCommon/buffer/ring_buffer.h
src/memory_counter.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/ring_buffer_test.cpp

Update memory-coutner for a cleaner solution and add comments.
- #91

Update memory counter

---

README.md
include/libKitsunemimiCommon/common_methods/string_methods.h
src/common_methods/string_methods.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.h

Add hexlify-method
- new unit-tests

Add hexlify

---

include/libKitsunemimiCommon/common_methods/object_methods.h
include/libKitsunemimiCommon/common_methods/string_methods.h
src/common_methods/object_methods.cpp
src/common_methods/string_methods.cpp
src/src.pro
tests/unit_tests/libKitsunemimiCommon/common_methods/object_methods_test.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/object_methods_test.h
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.h
tests/unit_tests/libKitsunemimiCommon/common_methods/vector_methods_test.cpp
tests/unit_tests/main.cpp
tests/unit_tests/unit_tests.pro

move hexlify methods into a new file
- unit-tests

move hexlify methods into a new file

---

CHANGELOG
README.md
src/src.pro

changes for tagging 0.14.0

---

.gitlab-ci.yml
build.sh
libKitsunemimiCommon.pro
src/common_items/data_items.cpp
src/common_items/table_item.cpp
src/common_methods/string_methods.cpp
src/process_execution.cpp
src/test_helper/speed_test_helper.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/stack_buffer_reserve_test.cpp

Make tests optional

---

CHANGELOG
src/src.pro

changes for tagging 0.14.1

---

include/libKitsunemimiCommon/threading/event.h
include/libKitsunemimiCommon/threading/thread.h
include/libKitsunemimiCommon/threading/thread_handler.h
src/src.pro
src/threading/event.cpp
src/threading/thread.cpp
src/threading/thread_handler.cpp

- Add event queue to thread-class
- #99 
- not tested now

Add event queue

---

.gitlab-ci.yml
README.md
echo
include/libKitsunemimiCommon/test_helper/compare_test_helper.h
include/libKitsunemimiCommon/test_helper/memory_leak_test_helper.h
src/common_items/table_item.cpp
src/memory_counter.cpp
src/src.pro
src/test_helper/compare_test_helper.cpp
src/test_helper/memory_leak_test_helper.cpp
tests/memory_leak_tests/libKitsunemimiCommon/buffer/data_buffer_test.cpp
tests/memory_leak_tests/libKitsunemimiCommon/buffer/data_buffer_test.h
tests/memory_leak_tests/libKitsunemimiCommon/buffer/ring_buffer_test.cpp
tests/memory_leak_tests/libKitsunemimiCommon/buffer/ring_buffer_test.h
tests/memory_leak_tests/libKitsunemimiCommon/buffer/stack_buffer_reserve_test.cpp
tests/memory_leak_tests/libKitsunemimiCommon/buffer/stack_buffer_reserve_test.h
tests/memory_leak_tests/libKitsunemimiCommon/buffer/stack_buffer_test.cpp
tests/memory_leak_tests/libKitsunemimiCommon/buffer/stack_buffer_test.h
tests/memory_leak_tests/libKitsunemimiCommon/common_items/data_items_test.cpp
tests/memory_leak_tests/libKitsunemimiCommon/common_items/data_items_test.h
tests/memory_leak_tests/libKitsunemimiCommon/common_items/table_item_test.cpp
tests/memory_leak_tests/libKitsunemimiCommon/common_items/table_item_test.h
tests/memory_leak_tests/libKitsunemimiCommon/state_test.cpp
tests/memory_leak_tests/libKitsunemimiCommon/state_test.h
tests/memory_leak_tests/libKitsunemimiCommon/statemachine_test.cpp
tests/memory_leak_tests/libKitsunemimiCommon/statemachine_test.h
tests/memory_leak_tests/main.cpp
tests/memory_leak_tests/memory_leak_tests.pro
tests/tests.pro

Add memory leak test helper and memory-leak-tests
- #102 
- new tests

Add memory leak test helper

---

CHANGELOG
src/src.pro

changes for tagging 0.15.0

---

CHANGELOG
src/src.pro

changes for tagging 0.15.1

---

include/libKitsunemimiCommon/threading/event.h
src/common_items/data_items.cpp

Fix events
- #112 
- tested in context of this issue: https://github.com/kitsudaiki/libKitsunemimiSakuraMessaging/issues/7

Fix events

---

CHANGELOG
src/src.pro

updates for tagging 0.15.2
- #114 
- ci-pipeline

updates for tagging 0.15.2

---

include/libKitsunemimiCommon/threading/cleanup_thread.h
src/src.pro
src/threading/cleanup_thread.cpp

add modified version of the cleanup-thread from libKitsunemimiNetwork
- #116 
- not tested at the moment

add modified version of the cleanup-thread from libKitsunemimiNetwork

---

include/libKitsunemimiCommon/threading/cleanup_thread.h
include/libKitsunemimiCommon/threading/thread.h
include/libKitsunemimiCommon/threading/thread_handler.h
src/threading/cleanup_thread.cpp
src/threading/thread.cpp
src/threading/thread_handler.cpp

Cleanup thead handling
- #118 
- tested in libKitsunemimiNetwork

Cleanup thead handling

---

src/statemachine.cpp
src/threading/barrier.cpp
tests/memory_leak_tests/libKitsunemimiCommon/common_items/data_items_test.cpp

Add missing memory leak test
- #110 
- ci-pipeline

Add missing memory leak test

---

CHANGELOG
src/src.pro

updates for tagging 0.16.1
- #123 
- ci-pipeline

updates for tagging 0.16.1

---

README.md
include/libKitsunemimiCommon/common_methods/object_methods.h
src/common_methods/object_methods.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/object_methods_test.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/object_methods_test.h

Add base64 encode decode
- #111 
- new unit-tests

Add base64 encode decode

---

CHANGELOG
src/src.pro

updates for tagging 0.17.1
- ci-pipeline

updates for tagging 0.17.1

---

README.md
include/libKitsunemimiCommon/buffer/item_buffer.h
src/buffer/item_buffer.cpp
src/src.pro
tests/memory_leak_tests/libKitsunemimiCommon/buffer/item_buffer_test.cpp
tests/memory_leak_tests/libKitsunemimiCommon/buffer/item_buffer_test.h
tests/memory_leak_tests/main.cpp
tests/memory_leak_tests/memory_leak_tests.pro
tests/unit_tests/libKitsunemimiCommon/buffer/item_buffer_test.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/item_buffer_test.h
tests/unit_tests/main.cpp
tests/unit_tests/unit_tests.pro

Add item buffer
- #130 
- new unit- and memory-leak tests in ci-pipeline

Add item buffer

---

CHANGELOG
src/src.pro
tests/unit_tests/libKitsunemimiCommon/buffer/item_buffer_test.cpp

- update for tagging 0.18.0
- #132 
- ci-pipeline

Tag 0.18.0

---

include/libKitsunemimiCommon/buffer/item_buffer.h
libKitsunemimiCommon.pro
src/buffer/item_buffer.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/item_buffer_test.cpp
tests/unit_tests/unit_tests.pro

Allow static part in item buffers
- #135 
- ci-pipeline

Allow static part in item buffers

---

README.md
include/libKitsunemimiCommon/progress_bar.h
src/progress_bar.cpp
src/src.pro
tests/unit_tests/libKitsunemimiCommon/progress_bar_test.cpp
tests/unit_tests/libKitsunemimiCommon/progress_bar_test.h
tests/unit_tests/main.cpp
tests/unit_tests/unit_tests.pro

add progress-bar
- #137 
- updated unit-tests

add progress-bar

---

README.md
src/src.pro
tests/tests.pro

update to cpp17
- https://github.com/kitsudaiki/Kitsunemimi-Project-Meta/issues/4
- ci-pipeline

update to cpp17

---

README.md
include/libKitsunemimiCommon/common_methods/file_methods.h
include/libKitsunemimiCommon/files/binary_file.h
include/libKitsunemimiCommon/files/text_file.h
include/libKitsunemimiCommon/logger.h
src/common_methods/file_methods.cpp
src/files/binary_file.cpp
src/files/text_file.cpp
src/logger.cpp
src/src.pro
tests/memory_leak_tests/memory_leak_tests.pro
tests/unit_tests/libKitsunemimiCommon/common_methods/file_methods_test.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/file_methods_test.h
tests/unit_tests/libKitsunemimiCommon/files/binary_file_with_directIO_test.cpp
tests/unit_tests/libKitsunemimiCommon/files/binary_file_with_directIO_test.h
tests/unit_tests/libKitsunemimiCommon/files/binary_file_without_directIO_test.cpp
tests/unit_tests/libKitsunemimiCommon/files/binary_file_without_directIO_test.h
tests/unit_tests/libKitsunemimiCommon/files/text_file_test.cpp
tests/unit_tests/libKitsunemimiCommon/files/text_file_test.h
tests/unit_tests/libKitsunemimiCommon/logger_test.cpp
tests/unit_tests/libKitsunemimiCommon/logger_test.h
tests/unit_tests/main.cpp
tests/unit_tests/unit_tests.pro

Add parts of libKitsunemimiPersistence
- #144 
- ci-pipeline

Add parts of libKitsunemimiPersistence

---

.gitlab-ci.yml
src/common_methods/file_methods.cpp
tests/unit_tests/libKitsunemimiCommon/files/text_file_test.cpp

fix ci-pipeline

---

CHANGELOG
README.md
src/src.pro

updates for tagging 0.20.0
- #148 
- ci-pipeline

updates for tagging 0.20.0

---

include/libKitsunemimiCommon/threading/thread.h
src/threading/thread.cpp

update thread-binding for more flexible usage
- #150 
- manually testing in separate project

update thread-binding for more flexible usage

---

README.md
include/libKitsunemimiCommon/common_methods/string_methods.h
src/common_methods/string_methods.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/string_methods_test.h

add functions to string to upper and to lower case
- #165 
- new unit-tests in ci

add functions to string to upper and to lower case

---

include/libKitsunemimiCommon/common_items/table_item.h
src/common_items/table_item.cpp
tests/unit_tests/libKitsunemimiCommon/common_items/table_item_test.cpp
tests/unit_tests/libKitsunemimiCommon/common_items/table_item_test.h

allow stealing of table-content
- #169 
- new unit-tests in ci-pipeline

allow stealing of table-content

---

include/libKitsunemimiCommon/buffer/ring_buffer.h

make getter for ring-buffer const
- #172 
- ci-pipeline

make getter for ring-buffer const

---

include/libKitsunemimiCommon/common_methods/file_methods.h
include/libKitsunemimiCommon/files/text_file.h
src/common_methods/file_methods.cpp
src/files/text_file.cpp
tests/unit_tests/libKitsunemimiCommon/common_methods/file_methods_test.cpp
tests/unit_tests/libKitsunemimiCommon/files/text_file_test.cpp
tests/unit_tests/libKitsunemimiCommon/logger_test.cpp

add error-container to file-related functions
- #174 
- update unit-tests in ci-pipeline

add error-container to file-related functions

---

CHANGELOG
src/src.pro

updates for tagging 0.23.0
- #178 
- ci-pipeline

updates for tagging 0.23.0

---

src/common_methods/string_methods.cpp

improve speed of string-split-operations
- #180 
- ci-pipeline

improve speed of string-split-operations

---

README.md
include/libKitsunemimiCommon/common_items/table_item.h
src/common_items/table_item.cpp
tests/unit_tests/libKitsunemimiCommon/common_items/table_item_test.cpp

change table-row from map to array
- #185 
- updated ci-pipeline

change table-row from map to array

---

CHANGELOG
src/src.pro

updates for tagging 0.24.0
- #187 
- ci-pipeline

updates for tagging 0.24.0

---

include/libKitsunemimiCommon/threading/thread.h
src/threading/thread.cpp

update thread-binding to choose a list fo cores instead of one
- #191 
- ci-pipeline

update thread-binding to choose a list fo cores instead of one

---

CHANGELOG
src/src.pro

updates for tagging 0.25.1
- #196 
- ci-pipeline

updates for tagging 0.25.1

---

include/libKitsunemimiCommon/files/binary_file.h
src/files/binary_file.cpp
tests/unit_tests/libKitsunemimiCommon/files/binary_file_with_directIO_test.cpp
tests/unit_tests/libKitsunemimiCommon/files/binary_file_with_directIO_test.h
tests/unit_tests/libKitsunemimiCommon/files/binary_file_without_directIO_test.cpp
tests/unit_tests/libKitsunemimiCommon/files/binary_file_without_directIO_test.h

feat: add new write-function to binary-files for plain data-pointer
- #198 
- updated unit-tests in ci-pipeline

feat: add new write-function to binary-files for plain data-pointer

---

include/libKitsunemimiCommon/files/binary_file.h
src/files/binary_file.cpp
tests/unit_tests/libKitsunemimiCommon/files/binary_file_with_directIO_test.cpp
tests/unit_tests/libKitsunemimiCommon/files/binary_file_with_directIO_test.h
tests/unit_tests/libKitsunemimiCommon/files/binary_file_without_directIO_test.cpp
tests/unit_tests/libKitsunemimiCommon/files/binary_file_without_directIO_test.h

- feat: add new read-function for binaray-files
- #200 
- ci-pipeline

feat: add new read-function for binaray-files

---

src/files/binary_file.cpp

fix: fixed checks in binary-files, which were added in the last ticket
- #200
- ci-pipeline and manually test while using the repository in another project

fix: fixed checks in binary-files, which were added in the last ticket

---

src/common_items/data_items.cpp

Remove compile warnings in data items
- #205 
- ci-pipeline

Remove compile warnings in data items

---

CHANGELOG
src/src.pro

updates for tagging 0.25.2
- #207 
- ci-pipeline

updates for tagging 0.25.2

---

CHANGELOG
src/src.pro

updates for tagging 0.25.3
- #211 
- ci-pipeline

updates for tagging 0.25.3

---

include/libKitsunemimiCommon/statemachine.h
include/libKitsunemimiCommon/threading/event_queue.h
src/src.pro
src/state.h
src/statemachine.cpp
src/threading/event_queue.cpp
tests/memory_leak_tests/libKitsunemimiCommon/statemachine_test.cpp

Add event trigger in statemachine states
- #214 
- #213 
- standard ci-pipeline with at least updated memory-leak-tests
- new feature itself not tested yet

Add event trigger in statemachine states

---

include/libKitsunemimiCommon/buffer/item_buffer.h
src/buffer/item_buffer.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/item_buffer_test.cpp
tests/unit_tests/libKitsunemimiCommon/buffer/item_buffer_test.h

Feat: restructure item-buffer to allow easy backup and restore
- #216 
- updates unit-tests

Feat: restructure item-buffer to allow easy backup and restore
